### ISSUE TITLE
Error al presentar exactitud

### ISSUE THREAD

**Issue by danielgomez2501** [danielgomez2501/ICCH#4]
Se presenta un error luego de realizar el entrenamiento de la interfaz, que provoca que se cierre toda la aplicación, lo que indica que este error muy probablemente sucede en la interfaz principal, no en los hilos donde se ejecuta el entrenamiento.

Se presenta el siguiente mensaje:

`Traceback (most recent call last):
   File "/home/alego/Proyectos/ICCH/Interfaz.py", line 679, in <module>
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/home/alego/venv10/lib64/python3.10/site-packages/kivy/clock.py", line 776, in post_idle
     self._process_events()
   File "kivy/_clock.pyx", line 620, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 653, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "/home/alego/Proyectos/ICCH/Interfaz.py", line 227, in actualizar
     self.avance()
   File "/home/alego/Proyectos/ICCH/Interfaz.py", line 275, in avance
     Resumen.metricas()
   File "/home/alego/Proyectos/ICCH/Interfaz.py", line 469, in metricas
     ((metricas['Id'] == int(Modelo.ubi))
 AttributeError: 'Modelo' object has no attribute 'Exactitud'. Did you mean: 'exactitud'?
Segmentation fault (core dumped)
`

**Comment by danielgomez2501** [comment]
Se corrige el error, resuelto por la recomendación que da al final el mensaje de error
